name: Weekly SKLC Report

on:
  schedule:
    # Monday 10 PM IST
    - cron: '30 16 * * 1'

  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Function
        run: |
          curl -X POST \
          https://tqxtfenwsgfolcfdnurk.supabase.co/functions/v1/weekly-report
